---
# This is the configuration for SideCar OpenTelemetry Collector.
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-otel
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols: 
          grpc:
          http:
    processors:
    exporters:
      logging:
        verbosity: detailed
      zipkin:
        endpoint: "http://ec2-44-232-240-174.us-west-2.compute.amazonaws.com:9411/api/v2/spans"
        format: proto
      otlp/jaeger:
        endpoint: "ec2-44-232-240-174.us-west-2.compute.amazonaws.com:5317"
        tls:
          insecure: true
      otlphttp/appdotelcol:
        endpoint: http://opentelemetry-demo-otelcol:4318
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlphttp/appdotelcol]
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, zipkin, otlp/jaeger, otlphttp/appdotelcol]
        logs:
          receivers: [otlp]
          exporters: [logging, otlphttp/appdotelcol]
      telemetry:
        logs:
          level: "debug"
